# Walmart Data Analysis and PostgreSQL Ingestion Pipeline

This notebook demonstrates a data preprocessing and database ingestion pipeline for Walmart sales data.

## 1. Setup & Environment Verification

Importing required libraries and checking Pandas version to verify setup.

In [34]:
# Import required libraries for data manipulation and database connectivity
#
import pandas as pd
import psycopg2
print("Pandas version:", pd.__version__)

Pandas version: 3.0.5

## 2. Load Dataset

Loading the Walmart sales dataset from the CSV file.

In [7]:
# Load the Walmart dataset, ignoring any encoding errors
#
df=pd.read_csv("Walmart.csv",encoding_errors='ignore')

### 2.1 Preview Sample Data

Viewing the first few rows of the DataFrame to inspect its structure and values.

In [10]:
# Display the first 5 rows of the DataFrame
#
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

### 2.2 Descriptive Statistics

Generating summary statistics for the dataset.

In [17]:
# Generate summary statistics
#
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

### 2.3 Data Structure Info

Inspecting columns, data types, and non-null counts.

In [18]:
# Display DataFrame information (data types, memory usage, non-null counts)
#
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

## 3. Data Quality & Cleaning

### 3.1 Check for Missing Values

Analyzing the count of missing (null) values in each column.

In [19]:
# Count missing (null) values in each column
#
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

### 3.2 Check for Duplicate Rows

Identifying duplicate records in the dataset.

In [22]:
# Count the number of duplicate rows
#
df.duplicated().sum()

np.int64(0)

### 3.3 Remove Duplicate Rows

Removing duplicate records to ensure data uniqueness.

In [21]:
# Remove duplicate rows in-place
#
df.drop_duplicates(inplace=True)

### 3.4 Verify DataFrame Shape

Checking the dimensions of the DataFrame after deduplication.

In [25]:
# Display the dimensions (rows, columns) of the DataFrame
#
df.shape

(10000, 11)

### 3.5 Check DataFrame Info After Deduplication

Reviewing the non-null counts and updated index after removing duplicates.

In [28]:
# Display updated DataFrame information
#
df.info()

<class 'pandas.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   str
 2   City            9969 non-null   str
 3   category        9969 non-null   str
 4   unit_price      9969 non-null   str
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   str
 7   time            9969 non-null   str
 8   payment_method  9969 non-null   str
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(3), int64(1), str(7)
memory usage: 934.6 KB

### 3.6 Handle Missing Values

Dropping rows containing any null values to ensure data completeness.

In [27]:
# Drop rows with null values in-place
#
df.dropna(inplace=True)

### 3.7 Data Cleaning: Format Unit Price

Removing the dollar sign ($) symbol from the `unit_price` column to enable numerical operations.

In [29]:
# Remove '$' symbol from 'unit_price' column
#
df['unit_price'] = df['unit_price'].str.replace("$","")

### 3.8 Verify Format Change

Checking sample rows to ensure the formatting change was applied correctly.

In [30]:
# Check the first few rows to verify the '$' removal
#
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

### 3.9 Type Casting: Convert Unit Price to Numeric

Converting the cleaned `unit_price` column from string type to float data type.

In [31]:
# Convert 'unit_price' column to float data type
#
df['unit_price']=df['unit_price'].astype(float)

### 3.10 Verify Data Type Conversion

Confirming that the `unit_price` column is now of float type.

In [ ]:
# Check DataFrame info to verify the data type conversion of 'unit_price'

df.info()

<class 'pandas.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   str
 2   City            9969 non-null   str
 3   category        9969 non-null   str
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   str
 7   time            9969 non-null   str
 8   payment_method  9969 non-null   str
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), str(6)
memory usage: 934.6 KB

## 4. Database Connection & Data Ingestion

### 4.1 Establish Connection to PostgreSQL

Creating a database connection using SQLAlchemy and psycopg2.

In [35]:
# Setup connection to PostgreSQL database using SQLAlchemy
#

from sqlalchemy import create_engine

# psql connection
engine_psql = create_engine("postgresql+psycopg2://postgres:121212@Localhost:5432/walmart_db")
try:
    engine_psql
    print("Connection to PostgreSQL database successful")
except:
    print("Failed to connect to PostgreSQL database")

Connection to PostgreSQL database successful

### 4.2 Ingest Data to PostgreSQL

Exporting the cleaned DataFrame into the PostgreSQL table `walmart`.

In [36]:
# Write the DataFrame to the 'walmart' table in the database (replace if exists)
#
df.to_sql(name='walmart',con=engine_psql,if_exists='replace',index=False)

969